### ISSUE TITLE
Problems with skip forward/back buttons and keyboard shortcuts

### ISSUE THREAD

**Issue by JonnyHaystack** [jellyfin/jellyfin-web#1079]
**Describe the bug**

At first when you start watching a video, the spacebar can be used to pause/unpause playback. This is normal behaviour that anyone would expect, having used YouTube, Plex, or pretty much anything else with a video player.

When I skip forward or backward using either the buttons in the player UI or by using the left and right arrow keys, that works. But after skipping, the spacebar will no longer pause/unpause playback, but instead it will repeat whatever skip action you last took. For example, if I skip forward then try to pause, it will not pause but will skip forward by 30 seconds. It seems like the space bar is just pressing the last selected button element, and if that's one of the skip buttons, it presses them instead.

The only way to make it work again is to manually click the pause button in the UI, which is quite annoying to have to do after every time I skip something.

The arrow keys work correctly for skipping regardless of what element was last clicked, so the spacebar should too.

**To Reproduce**

1. Be watching a video
2. Press the spacebar and see that it correctly toggles pause
3. Skip forward or backward in the video either with the UI buttons or the arrow keys
4. Press the spacebar and see that it repeats the last skip action instead of toggling pause

**Expected behavior**

Pressing the spacebar during video playback should always toggle pause

**System (please complete the following information):**
 - OS: Server = Debian 10, Client = Arch Linux
 - Browser: qutebrowser
 - Jellyfin Version: 10.5.4

**Comment by dmitrylyzo** [comment]
`Space` just performs `click` on currently focused button (but not highlighted in non-TV layout). That's why (_I think_) this made such way: handle `Space` as pause only when OSD is hidden - no focused element.

Possible solutions (not tested):
- Ignore `click` with `Space`.
I am not sure, but maybe it is possible to `preventDefault` for `keydown` with `Space` for `emby-button`.
- Currently, `videoosd` catches `keydown` event but don't `stopPropagation`.
I wouldn't stick to this because I want to change (normalize) event handling (bubbling): element -> view -> keyboard navigation. So in the future it may break.

For both cases, need to move `Space` handling under `switch` - just `case "Space":` near `case "k":`.
