### ISSUE TITLE
Playback doesn't resume from correct position after going back if page not refreshed.

### ISSUE THREAD

**Issue by maaldheefee** [jellyfin/jellyfin-web#1372]
**Describe the bug**
Playback doesn't resume from correct position after going back if not refreshed.

**To Reproduce**
1. Open any media and play it.
2. Click the back button.
3. Resume the same media.

If the page is not refreshed after step 2, it resumes from the position that was saved previously before the most recent play.

**Expected behavior**
The playback should resume from where it's left off.

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox Developer Edition
 - Jellyfin Version: 10.5.5

**Additional context**
Also happens with [Jellyfin MPV Shim](https://github.com/iwalton3/jellyfin-mpv-shim/issues/74) (unofficial client). But doesn't happen on Android client.

Happens most of the time. Doesn't happen always.

**Comment by dkanada** [comment]
This is actually properly working in exactly one location, which is the main page. The carousel objects there will properly update every fifteen seconds or so with the progress and other information. This issue will probably have to wait until after the Vue migration though, because it would be extremely difficult to fix in the current code.
