### ISSUE TITLE
10.6.0 language doesn't change

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin-web#1446]
**Describe the bug**
When i try to change the language to another one and saved it, the language doesn't change.

**To Reproduce**

1. Dashboard > Server > General
2. prefered show language
3. French to English (united states) OR French to Italian
4. saved
5. F5
5. docker stop, delete, pull, run

the language is still in french

**System (please complete the following information):**
 - OS: docker linuxserver-jellyfin:nightly
 - Browser: Chrome
 - Jellyfin Version: 10.6.0

**Comment by MrTimscampi** [comment]
I believe this could be because there are translations on both sides.

The Dashboard one controls the server's language, while the one in Display > Settings controls the web client's language.

Ideally, we'd be able to pass the language to the API to get what we want.

@jellyfin/backend Any idea if there's something in the API to force a specific language on the server?

**Comment by EraYaN** [comment]
Not sure if it does anything but in the end `Accept-Language` should be the "source of truth" for the response language.
