### ISSUE TITLE
10.6.0  empty collections, do not show it

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin-web#1454]
**Describe the bug**
Hello,

When you create a new collection of movies, jellyfin adds a new collections category to the home page. When the collection is empty, the collections category remains on the home page.

**To Reproduce**

1. create a new collection
2. delete the collection
3. go  to the home page

**Expected behavior**
if the collection is empty do not show it

**System (please complete the following information):**
 - OS: docker
 - Browser: chrome
 - Jellyfin Version: linuxserver-jellyfin:nigthly

**Comment by DMouse10462** [comment]
Are you referring to the Collections library that appears alongside your other libraries? From the admin dashboard, you should be able to remove it like any other library from the "Libraries" section in the sidebar/menu. 

This is expected behavior for a library, but I can certainly see the reasoning for why an automatically created pseudo-library (if that's a good term for it) should also be automatically removed when it is empty. I'm curious to hear others' opinions on this.

**Comment by lelamamalgache** [comment]
> Are you referring to the Collections library that appears alongside your other libraries?
yes

> should also be automatically removed when it is empty
yes

> you should be able to remove it like any other library from the "Libraries" section in the sidebar/menu.
yes i did it manually to remove it
