### ISSUE TITLE
In certain scenarios with multiple clients, resume reporting is inaccurate

### ISSUE THREAD

**Issue by sparky8251** [jellyfin/jellyfin-web#1459]
**Describe the bug**
Noticed recently that if I leave my TV (web) client paused, then resume on my desktop the progress I make on the desktop appears to be overwritten by the paused TV client constantly.

This even goes so far as preventing me from manually parking the episode as fully watched in the web UI (via the checkmark).

**To Reproduce**
1. open 2 different clients and get 1 of them to the point of being resumable
2. on the 2nd client, watch to the end and notice that the playback is still reported as whereever client 1 is
3. try using the checkmark to mark it as complete and notice that while you can mark it as unwatched properly, every time you try and mark is as complete it will take on the resume point of client 1
4. stop being lazy and walk 5 feet to end playback on client 2, then grumble about the devs

**Expected behavior**
I would expect playback reporting to be accurate regardless of number of clients.

**System (please complete the following information):**
 - Jellyfin Version: nightly

**Comment by dkanada** [comment]
This sounds like a design issue rather than an actual bug. I'm guessing client two reports playback completion and 100% progress after exiting the stream, but since client one is still open it continues to report progress at the current location. Progress is tracked independently from watch state, so if you want to simply disable progress when watched, this is an issue with the web client. I can't think of another method to improve the situation, since we don't want to break progress reporting just because an item has been marked as watched.

**Comment by maaldheefee** [comment]
#1372 might be related to this
