### ISSUE TITLE
Duplicate 'TheMovieDb Id' entry

### ISSUE THREAD

**Issue by sang-ook** [jellyfin/jellyfin-web#1580]
**Describe the bug**

Identify pop-up contains two 'TheMovieDb Id' entries.

**To Reproduce**

1. Select some movie
2. Click on 'More'
3. Select 'Identify'
4. See two 'TheMovieDb Id' entries

**Expected behavior**

There should be only one 'TheMovieDb Id' entry.

**Logs**

**Screenshots**

![Screenshot from 2020-07-17 09-46-52](https://user-images.githubusercontent.com/67825889/87762320-78c6b680-c802-11ea-8ecf-e85e5642f96a.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Jellyfin Version: 10.5.5

**Additional context**

**Comment by cvium** [comment]
I think the last one might be a Collection is

**Comment by MrTimscampi** [comment]
Thanks for the report :)

The second one is indeed the Collection ID and this particular issue  has already been fixed for 10.6::

![image](https://user-images.githubusercontent.com/19396809/87764098-1b3c6500-c816-11ea-929a-9e26ce2c7a89.png)

As such, I'll close this so that we don't track already fixed issues.
