### ISSUE TITLE
Books are displayed in 4:3 in the library view.

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin-web#1614]
![image](https://user-images.githubusercontent.com/65789901/86548050-95bdd880-bf2a-11ea-8f6d-2554c1601aa8.png)
Books don't display their full sized covers, cant find any setting for it so im assuming its a bug.

**Comment by dkanada** [comment]
This is technically a server issue, because it isn't reporting the aspect ratio correctly. I'm not even sure why we need to calculate the aspect ratio on the server though. Seems like we should just use sane defaults on all clients (books and movies use posters, artists and albums use squares, et cetera) and avoid the extra computational requirements for scans.

cc @Bond-009 because I think computing the size takes ages during scans

**Comment by Darkwolf1515** [comment]
I mean, it still is an issue, so.

**Comment by grafixeyehero** [comment]
@Darkwolf1515 https://github.com/jellyfin/jellyfin-web/blob/014a97ef97c8f413e00ed76ed8f8f0080c7c18cd/src/components/cardbuilder/cardBuilder.js#L309-L311

change to this until i found a better solution
`if (!options.shape) {
  options.shape = options.defaultShape || (requestedShape === 'autooverflow' ? 'overflowPortrait' : 'portrait');
}`

**Comment by Darkwolf1515** [comment]
stil
