### ISSUE TITLE
set default album thumbnail if no cover art is found

### ISSUE THREAD

**Issue by dkanada** [jellyfin/jellyfin-web#18]
This applies to the `itemdetails` view for both mobile and desktop, which show an empty section where the cover art would normally be shown. Ideally it would display the same default thumbnail that shows up for other album views. The same fix could eventually be applied to all media types in `itemdetails` since I believe this is an issue for all of them.

related to #15

**Comment by drago-96** [comment]
I have a sort of fix (i.e.show the colored square with the disc icon instead of the white image), but I think we should have a more general plan about this.
For example, at the moment if I have a backdrop for an artist, but not the album image, in the list of all albums and on mobile `itemdetail` I see that backdrop image, but on the desktop `itemdetail` there is the white (or the yellow/purple/whatever with this fix) image.

**Comment by dkanada** [comment]
@drago-96 I don't think we need to keep a persistent color for the placeholder yet. If you still have your solution that adds the disc placeholder a PR would be welcome. It would be cool if we could eventually implement something like [blurhash](https://blog.joinmastodon.org/2019/05/improving-support-for-adult-content-on-mastodon/) before images load completely, which would solve the problem of slow image loads entirely.
