### ISSUE TITLE
Watch state is changed to unwatched when watched item is played again

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [jellyfin/jellyfin-web#1977]
**Describe The Bug**
A titles watch state is changed to unwatched when it is played after being watched

**Steps To Reproduce**

1. Mark a title as watched
2. Play it
3. Observe the watch state has changed to unwatched.

**Expected Behavior**
For the items watch state not to change to unwatched? (I *think?*)

**Logs**
n/a

**Screenshots**
n/a

**System (please complete the following information):**
 - Platform: Windows and Android
 - Browser: Chromium
 - Jellyfin Version: 10.6.4

**Comment by bugfixin** [comment]
I think this makes more sense in the server repository - it looks like the culprit is likely the UpdatePlayState in UserDataManager.cs. It seems to pretty directly link playback progress against play state.

Whether unlinking played status and playback position is something that makes sense, that's up to the jellyfin team.
