### ISSUE TITLE
Replace remote fonts with local hosted fonts

### ISSUE THREAD

**Issue by Anan5a** [jellyfin/jellyfin-web#2048]
**Describe The Bug**
Right now fonts are loaded from repo.jellyfin.org which causes CORS error,
Please replace it with Locally hosted files

**Steps To Reproduce**

**Expected Behavior**

**Logs**

**Screenshots**

![Screenshot_20201108_132505](https://user-images.githubusercontent.com/16373480/98459561-3ae10a00-21c6-11eb-98af-ffa82d1ca1c3.png)

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Firefox, Chrome, Brave
 - Jellyfin Version: 10.7.0
**Additional Context**

**Comment by dkanada** [comment]
There's an issue with the web server configuration right now that's causing those errors. We don't plan on moving to locally hosted fonts because it needlessly balloons the web client size, but this was added with configurability in mind. There has been a config file for the web client since 10.4.0 and it now includes a section to load fonts as desired. This will probably extend to the fonts used by SubtitlesOctopus for SSA subtitles at some point as well.

**Comment by gr01d** [comment]
I second this, it is a bad idea to use online fonts. It defeats the purpose of self hosting. I also saw requests from Google Static (gstatic.co m) from the login page.

**Comment by thornbill** [comment]
This has been fixed for 10.7.
