### ISSUE TITLE
Use webpack for building and minifying.

### ISSUE THREAD

**Issue by EraYaN** [jellyfin/jellyfin-web#21]
This project really needs a proper bundler. Will see if any of my existing webpack template files will work.

We should also switch to yarn as a package manager.

2019-09-30:
We need to build the actual application bundle as well as just the dependency bundle and minify.

**Comment by anthonylavado** [comment]
Is this done then?

**Comment by thornbill** [comment]
Well we did make the switch to using yarn and we use webpack for building. There are definitely some improvements that can be made to the webpack build as it currently only bundles dependencies though. So perhaps we should just update this ticket with the progress and what remains to be done.

**Comment by brianjmurrell** [comment]
I'm a total newb when it comes to yarn and webpack and whatnot.  But I've gathered the process is to run `yarn install` inside this repo.

That seems to install some stuff:

```
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
```

Two things:
1. Is the error in the above concerning
1. Does running the above on different platforms (linux, windows, macos, etc.) result in different dependencies being installed?

If the answer to the last question above is no, can this stuff not be fetched and included with the release tarballs so that building doesn't require Internet/npm repo access?

**Comment by thornbill** [comment]
1. That error is not a concern. I _believe_ that package is used by webpack on some operatings systems to support watching for file system changes. This allows webpack to trigger builds automatically when files change during development.
2. In the case above some development tools may need additional packages to support functionality used for building the package, but this should never be the case for the non-development dependencies that get bundled by webpack into the final jellyfin-web package.

Yes it is possible to build and distribute a copy of `jellyfin-web` so that yarn is not needed for the server build. `yarn pack` will build a tarball that would be identical to what would be published to npm. This was something that we worked on leading up to 10.4, but didn't arrive at a good solution on _how_ to handle including `jellyfin-web`.

**Comment by brianjmurrell** [comment]
So am I reading between the lines then that the intention is that at some point jellyfin-web releases (i.e. https://github.com/jellyfin/jellyfin-web/releases) will be made with everything that yarn brings into jellyfin-web such that the tarball contains everything needed?

To be sure, having self-contained tarballs in https://github.com/jellyfin/jellyfin-web/releases doesn't mean having to commit the result of the `yarn ...` commands into the repo.  You could create a github action that creates releases by executing the `yarn ...` commands needed to create this self-contained tarball and not have to pollute your repo with that stuff.

**Comment by anthonylavado** [comment]
I mean, I'm sure we could automate it somewhere. I just don't think we have at this point. It's only done when a proper build is kicked off at the moment.

As noted, we don't have to do this on our servers either. It could be a GitHub Action, or Azure like we do with everything else CI related.

**Comment by thornbill** [comment]
We already build a tarball as part of the Azure Pipeline for jellyfin-web. 😉 So some of the necessary pieces are in place, but there is still a lot of work to do to get all the right things in all the right places.

**Comment by EraYaN** [comment]
I mean actually just publishing all created tarballs is probably a bad idea. CI can do it (check the docs repo), but it results in TONS of releases. It should probably just be a nightly build.

**Comment by brianjmurrell** [comment]
Yes, I am just referring to creating post-*yarn*ed tarballs for actual [releases](https://github.com/jellyfin/jellyfin-web/releases).

**Comment by brianjmurrell** [comment]
Piss off @stale-bot.
