### ISSUE TITLE
[10.7.2] No poster images / Low quality card images on high DPI displays

### ISSUE THREAD

**Issue by ottodoesntknow** [jellyfin/jellyfin-web#2587]
**Describe The Bug**
Since the last 10.7.2 update I'm seeing low quality images being used for the cards (posters, thumbs and library images). This is a Jellyfin Web issue as I can see them in high quality using Jellyfin Vue.

**Steps To Reproduce**
1. Update to 10.7.2
2. Go to the main page and look at the card images

**Expected Behavior**
Clear and high quality images being used for the cards.

**Screenshots**
Jellyfin Web:
![image](https://user-images.githubusercontent.com/26852261/114350093-086a7d00-9b69-11eb-9c4a-d1d474883dd2.png)
![image](https://user-images.githubusercontent.com/26852261/114350216-3354d100-9b69-11eb-9ca4-e21b1f867ab8.png)
![image](https://user-images.githubusercontent.com/26852261/114350283-4bc4eb80-9b69-11eb-9b2e-7c2a60213f83.png)

Jellyfin Vue:
![image](https://user-images.githubusercontent.com/26852261/114350134-16200280-9b69-11eb-8aad-11240c916fd3.png)
![image](https://user-images.githubusercontent.com/26852261/114350253-4071c000-9b69-11eb-83b9-a4ae7879407d.png)
![image](https://user-images.githubusercontent.com/26852261/114350310-55e6ea00-9b69-11eb-8ffc-35404aa998a8.png)

**System (please complete the following information):**
 - Platform: Docker 20.10.5 on Ubuntu Server 20.04.2 LTS
 - Browser: Edge Chromium 91.0.845.2 (Dev)
 - Jellyfin Version: 10.7.2 (Hotio Docker image)

**Comment by oddstr13** [comment]
Could you please provide the URLs of the images?

**Comment by ThibaultNocchi** [comment]
You can get info in #2191

**Comment by ottodoesntknow** [comment]
> Could you please provide the URLs of the images?
Movie poster:
http://192.168.0.19:8096/Items/d218622baae752ed2d1018a27bcd170d/Images/Primary?fillHeight=329&fillWidth=219&tag=bdecbcb1690aecb826f5f691e6dc7fa1&quality=90

Thumb:
http://192.168.0.19:8096/Items/c5ba59b06b6a5fdbb04f6377ca44e573/Images/Backdrop?fillWidth=358&tag=995c8bed7de61b4b815aa20940a8f115&quality=80

Library image:
http://192.168.0.19:8096/Items/1dbc59f98f7a5c0db1e7d825102c0336/Images/Primary?fillHeight=201&fillWidth=358&tag=8087f42dcce9f4ee8771832f66777749&quality=90

> Edit:
> It's _probably_ related to #2514, even if that was supposed to fix this exact issue for other images.
> Is this on a High DPI monitor?
Probably. I don't know how to check my exact DPI but I used [this site](https://www.sven.de/dpi/) and it gave me this:
![image](https://user-images.githubusercontent.com/26852261/114355755-24bde800-9b70-11eb-9660-33c9afdbebbe.png)

**Comment by yxwangcs** [comment]
I can confirm the issue with a 4K 27-inch monitor. With the same window size:

URL in 10.7.1:

Items/aafdf1b287b3438d26383b10f8353b5e/Images/Primary?**maxHeight=812&maxWidth=542**&tag=7c3b29d309eaaad83514d3711b75a6a6&quality=90


URL in 10.7.2:
Items/aafdf1b287b3438d26383b10f8353b5e/Images/Primary?**fillHeight=406&fillWidth=270.75**&tag=7c3b29d309eaaad83514d3711b75a6a6&quality=90

It seems that Jellyfin-web is unaware of the HiDPI monitor to request the correct height and width.

Also, while resizing the window, I noticed that sometimes the image won't load at all due to invalid width. 

For example, the request `Items/aafdf1b287b3438d26383b10f8353b5e/Images/Primary?fillHeight=424&fillWidth=282.5&tag=7c3b29d309eaaad83514d3711b75a6a6&quality=90` returns a 400 with the following error message:

```json
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-94729ea11d84d448bb0eea0c55182aa1-fedada3a38d15d46-00",
  "errors": {
    "fillWidth": [
      "The value '282.5' is not valid."
    ]
  }
}
```

I can create another issue if this is unrelated :)

**Comment by oddstr13** [comment]
Bleh, jellyfin/jellyfin-apiclient-javascript#167 didn't make it into the release then.

**Comment by TheNamelessWonderer** [comment]
@yxwangcs Your issue seems related to this one: https://github.com/jellyfin/jellyfin/issues/5788. Not sure if https://github.com/jellyfin/jellyfin/issues/5788 is related to this issue too.
