### ISSUE TITLE
XSS exploit in message sending.

### ISSUE THREAD

**Issue by DucksDont** [jellyfin/jellyfin-web#2674]
You can trigger an XSS exploit when you send messages to clients running jellyfin-web from the admin dashboard.

How to reproduce:
1. Go to your Jellyfin admin dashboard.
2. Send a message to any client running jellyfin-web with this text:  `"><img src="http://fake.url.that.does.not.work" onerror=alert(1);>`
[In case you can't see the text](https://privatebin.ducksdont.net/?39b9e444e28fb351#7Xcbx76pZRGbdFWWXyrjEXsfCFWR3SYmuEjR15fy3oAv)

 - Platform: Linux
 - Browser: Firefox
 - Jellyfin Version: 10.7.2
 
 **Note**: I've only tested on FireFox.
 
I suggest filtering text client and server side to remove html elements.

I have also already sent an email to security@jellyfin.org about the issue.

**Comment by nielsvanvelzen** [comment]
I think the issue is in this line

https://github.com/jellyfin/jellyfin-web/blob/5c09077a2f12ae44e7b7d356ea8d9f35862b0b60/src/components/toast/toast.js#L25

It should set `textContent` instead of `innerHTML`. But the toast component might be used in places that require HTML.

**Comment by strugee** [comment]
Shouldn't there have been a GitHub advisory/CVE issued for this? Unless the argument is that the admin is assumed to be trusted anyway.

**Comment by nielsvanvelzen** [comment]
I don't think so. It is well known that a lot of places in our web client allow HTML. The impact of this issue is low, an administrator needs to explicitly inject some JavaScript or something similar to do harm to users, at that point they could just edit the `index.html` file manually. The fact that metadata from remote sources allows HTML would be a greater issue.
