### ISSUE TITLE
Can not reliably reorder playlists

### ISSUE THREAD

**Issue by joytrekker** [jellyfin/jellyfin-web#2684]
Version 10.7.5 in docker
Using jellyfin-web in jellyfin-media-player and Firefox nightly

When dragging and droping an item in a playlist it seems to be random chance if the item will stay where you drag it. Sometimes if you drag an item and refresh the page the wrong item gets moved. The item above the intended target gets moved instead.
The last item in a playlist can not be moved.

**Comment by joytrekker** [comment]
bump... This is still an issue.

**Comment by hkdd** [comment]
I'm also having this problem, also using Firefox.  Drag an item to reorder in a playlist, you get the spinning circle for a split second and it appears to reorder the list.  Navigate away and back, or refresh the page, and it has returned to the original (incorrect) order.

**Comment by joytrekker** [comment]
Bump again. Reordering is still broken,

**Comment by jschnurer** [comment]
Can confirm. Still an issue. Using Firefox or Edge produces the same results as previously described:

> Drag an item to reorder in a playlist, you get the spinning circle for a split second and it appears to reorder the list. Navigate away and back, or refresh the page, and it has returned to the original (incorrect) order.

I will also add that if you reorder the list, then click an item to play it, it will play the wrong song (presumably the song that was previously in that position before the reorder attempt).

When the user drops the item in the playlist to reorder it, an HTTP POST is made to /Playlists/xxxx/Items/yyyy/Move/zzz and successfully returns an HTTP204 No Content response so it doesn't appear to be an issue with the frontend.

Using version 10.7.6 from docker hub.

**Comment by enderdrag64** [comment]
I have this problem as well (latest version of jellyfin), I'm using Brave not Firefox so I don't think it's a browser issue

**Comment by fplanque** [comment]
I also have this issue with various browsers / Jellyfin on Windows.

**Comment by fplanque** [comment]
Same issue on Jellyfin / docker .

Version: 10.8.8

Operating System: Linux

Architecture: X64

**Comment by fplanque** [comment]
It seems the issue actually arises when the playlist contains a path to a file that is no longer there.

As it is pretty common to have tools to clean up the folder structure / rename files / remove duplicates, it would be really nice if the playlist could show the missing files instead of silently hiding them and then silently crashing when we try to reorder anything.

**Comment by kozmik-moore** [comment]
Can confirm that this is still an issue. Server is Ubuntu, clients are Firefox and Opera.

Can also confirm that the file path listed in the playlist.xml for one of the songs is broken as @fplanque mentioned.

**Comment by ojohnny** [comment]
I have the same problem with a playlist where I have updated metadata/renamed some files I had after it had been added to the playlist.

Do we have a workaround for "fixing" a broken playlist? (i.e. by not removing it and starting over from scratch)

The "broken entries" are not shown in the playlist view or in the metadata manager so I can't remove them from the playlist. Editing the xml by hand also does nothing since this only appears to be some kind of snapshot of the database.  I guess the only way is to remove it from the database by hand, but that sounds like the "wrong solution".

**Comment by ojohnny** [comment]
...replying to myself as I found a workaround:

1. In the "broken playlist", use three dots -> Add to playlist.
2. Create a new temporary playlist.  This new playlist can be reordered because it does not contain the broken entries.
3. Remove the old playlist.
4. Either rename the new playlist or add the items to a new playlist one more time but with the original playlist name.

**Comment by Arch-Storm** [comment]
Still an issue in 2024

**Comment by choochus** [comment]
For me it's not a matter of not being "reliable". I cannot reorder anything in playlists at all.

**Comment by thornbill** [comment]
Related server issue: https://github.com/jellyfin/jellyfin/issues/12892
