### ISSUE TITLE
10.7.6 debian serviceworker.js 'auto' prefix resulting in 404 errors

### ISSUE THREAD

**Issue by Nazar78** [jellyfin/jellyfin-web#2751]
**Describe The Bug**
From the latest 10.7.6 debian release, I noticed there's a lot of 404 not found errors when loading JF behind a reverse proxy on any browser. It doesn't happened from LAN access probably serviceworker.js wasn't loaded. Found the cause that the file 'web/serviceworker.js' has lots of 'auto' prefix when calling the assets e.g.

`'url': 'auto0095962de230e8e76d21c78c2130ce89.woff2'`

Not sure how to fix it in the codes so as a temporary solution I just sed regex remove the 'auto' prefix in the 'web/serviceworker.js' local file.

**Screenshots**

![image](https://user-images.githubusercontent.com/2883688/122663443-183bb880-d1cd-11eb-9bb1-243281c86901.png)

![image](https://user-images.githubusercontent.com/2883688/122663480-605adb00-d1cd-11eb-85bd-60f2ae2e7795.png)

**System (please complete the following information):**
 - Platform: Any
 - Browser: Any
 - Jellyfin Version: 10.7.6

**Comment by Dubwize** [comment]
I would like to add that this is happening to me also.   Currently on 10.7.5.

Doing the update to 10.7.6, and retesting.

**Comment by thornbill** [comment]
This was caused by a [dependency issue](https://github.com/GoogleChrome/workbox/issues/2649) with the workbox webpack plugin that is used to generate those paths. It is working as expected on master since that the plugin has been updated there. We are currently discussing internally the possibility of a 10.7.7 release to address this issue.
