### ISSUE TITLE
Vorbis audio always transcodes on web, even if the browser supports it.

### ISSUE THREAD

**Issue by michaelharmonart** [jellyfin/jellyfin-web#2788]
**Describe The Bug**

According to the codec support documentation, [here](https://jellyfin.org/docs/general/clients/codec-support.html) Vorbis is supported on every client, yet somehow, if I have audio transcoding allowed for the user, it always transcodes for the web. This happens even if I set the maximum allowed audio channels to 7.1. When I turn off audio transcoding the sound plays back just fine, but I can't change the audio track. The web browser handles all the downmixing from 7.1 or 5.1 with no issues, so why does it transcode if I allow the user to be able to transcode audio?
**Expected Behavior**

I would expect to be able to playback surround sound vorbis audio on chrome, firefox, etc. with no transcoding, as they support the format just fine.
**Logs**

No logs, but let me know it they are needed.

**System (please complete the following information):**
 - Platform: Linux (Manjaro)
 - Browser: Firefox, Chrome
 - Jellyfin Version: 10.7.6

**Comment by Artiume** [comment]
I'll have to add a note to that page. The issue is vorbis audio can only be contained by ogg, mkv and webm. If a file cannot be direct played, Jellyfin uses HLS via ffmpeg to provide the file. HLS uses .ts/mpegts to do this and so vorbis audio must be converted. You can test this by disabling audio conversion and then force a transcode but lowering the quality bitrate. That way the video converts but you get the vorbis audio. It should be silent or have glitchy audio in some form.

**Comment by michaelharmonart** [comment]
The problem is, I'm on chromium (brave specifically) which should support mkv containers according to that page. All my videos are in mkv files, and chrome should support mkv playback, why is the video being remuxed?

**Comment by cvium** [comment]
It's not entirely correct. MKV is not a supported container format in Chrome, _but_ WebM is and WebM is a subset of Matroska, so some MKV files can be played by Chrome.
