### ISSUE TITLE
Make pagination of libraries in the web UI optional/configurable

### ISSUE THREAD

**Issue by poulpor** [jellyfin/jellyfin-web#279]
**Describe the feature you'd like**
it would be great to have an option to change the maximum number of items displayed per page, actual limit is 100.

**Additional context**
I know it was possible with emby by modifying LibraryBrowser.js file, but  can't find it in Jellyfin docker container on my Synology Nas.

**Comment by chaosinnovator** [comment]
I'd like to tackle this as a first issue/feature since I'm new to the Jellyfin party. Looking to implement it as a infinite/lazy scroller. I can a couple ways to tackle this:

- Finite scroller with lazy item loading (and unloading). Libraries aren't truly infinite since there is a finite number of items. Would load items that are immediately visible plus a threshold above/below, and other items would be displayed either as placeholder item templates. Poster images unloaded when no longer visible. This would use more memory but be easier to implement.
- "Looping" scroller, ala Plex library view: when an item is scrolled out of view, its `<div>` gets "looped" to the other end of the scroller and filled with the new content. Item metadata would get loaded ~50+ at a time so titles can be filled right away and only images need to be fetched on scroll. This uses less memory, only using enough `<div>`s to fill the screen plus a threshold/spill area, but will be harder to implement (but maybe a better solution?), requiring (as far as I can tell) most of the `emby-itemscontainer` component to be re-written.

Ideally, the server API would return an `OffsetIndex` or `StartIndex` field with `/Item?` queries, to make it easier to track received metadata and avoid race conditions when scrolling fast, so I think I'll make a PR for that in the server repo first.

Since much of `emby-itemscontainer` component will need re-writing to accomplish this either way, and probably many of the implementations will also need some tweaks, would it be better just to create a new component (i.e. `infiniteitemscontainer`)?

**Comment by JustAMan** [comment]
I personally prefer paginated view (it survives refreshing), but can see a benefit of "infinite scroll" done Plex-y way.

**Comment by KristupasSavickas** [comment]
I'd like to give this a look. Is there a spec with the current HTTP API that Jellyfin exposes to the clients to use?

**Comment by MrTimscampi** [comment]
I don't believe we have a current API documentation, so looking into the code is likely your best bet.

I can give you more information as to where to look at the current implementation tonight (GMT+1)

**Comment by dkanada** [comment]
This will be a headache with the current library controllers. Those are actually one of the first things I want to figure out when we migrate to a framework, our current tabs solution is horrendously difficult to work with.

**Comment by KristupasSavickas** [comment]
> This will be a headache

Yeah that's what I figured

> when we migrate to a framework

Are there any concrete plans on what we're going to use?

**Comment by dkanada** [comment]
@KristupasSavickas #889

**Comment by MrTimscampi** [comment]
> This will be a headache with the current library controllers.

Turns out it's easier than expected, but there are multiple places to edit due to this thing being P O E T R Y.

It's also going to be slow on huge libraries because our lazy loader is still trash. But hey, first steps and all that.
