### ISSUE TITLE
Weirdness: Sort by is also a filter...

### ISSUE THREAD

**Issue by Madpeterz** [jellyfin/jellyfin-web#3358]
**Describe The Bug**
Sort by name selecting a letter applies a filter that does not reset on changing sort by option.

**Steps To Reproduce**
1. Go to movies
2. Click on Sort by
3. Select A-Z
4. Select a letter from the # A-Z menu on the right
5. Change sort by to release date

**Expected Behavior**
The Filter from the selected  # A-Z is cleared and the items sorted
by the new selection.

https://user-images.githubusercontent.com/57852827/150580382-6c81f792-365a-4b64-af81-c4b7e5f1c185.mp4

**Comment by dmitrylyzo** [comment]
IMO, `Sort by` is not a filter. It specifies how to order the filtered items.
The problem is that AlphaPicker has been hidden and there is no way to change or remove the name filtering.
https://github.com/jellyfin/jellyfin-web/blob/ac53b56b10a7751a2fbe25b5597491b82dd3f117/src/components/alphaPicker/alphaPicker.js#L290

How about leaving the AlphaPicker in place if `SortName` is in the list?
