### ISSUE TITLE
Urgently: Unstable releases are lost from repo.

### ISSUE THREAD

**Issue by WWWesten** [jellyfin/jellyfin-web#3455]
**Describe The Bug**

Unstable releases web & combined are lost from repo. Again.
Affected:
Debian
Ubuntu
Fedora (only 'web' from 23(?) Feb 22)
CentOS (only 'web' from 23(?) Feb 22)
Windows
Linux ('combined' from 5 Oct 21 and 'web' from 23 Feb 22)
MacOS ('combined' and 'web' from 23 Feb 22)

**Steps To Reproduce**

**Expected Behavior**

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: [e.g. Linux, Windows, iPhone, Tizen]
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: [e.g. 10.6.0]

**Additional Context**

**Comment by Shadowghost** [comment]
The builds are still there at https://repo.jellyfin.org/releases/server/debian/versions/unstable/

It's only the "overview" pages which seem to be broken. APT repo works fine too.

This will most likely not be fixed until the CI overhaul (will be done directly after 10.8 is branched off the master branch) because the scripts maintaining unstable are a mess.

**Comment by WWWesten** [comment]
Well. It is good that "back door" (which I didn't know about). ;)
