### ISSUE TITLE
Add webp image support for comicsPlayer

### ISSUE THREAD

**Issue by sulisu** [jellyfin/jellyfin-web#3619]
Just add webp ext to the following line in src/plugins/comicsPlayer/plugin.js, then it works.

```
// the comic book archive supports any kind of image format as it's just a zip archive
const supportedFormats = ['jpg', 'jpeg', 'jpe', 'jif', 'jfif', 'jfi', 'png', 'avif', 'gif', 'bmp', 'dib', 'tiff', 'tif'];
```

I don't get the idea why even avif is in the list, while webp doesn't show up here. More browsers support webp than avif.

**Comment by MinecraftPlaye** [comment]
> I don't get the idea why even avif is in the list, while webp doesn't show up here. More browsers support webp than avif.

Very simple reason: When I wrote that list of image formats, I put in all image formats I knew about.
In theory, instead of filtering for images, one could also filter for metadata files, but as comics don't have any standard in that regard, it's just the same problem on the other end: An endless list of files/file extensions that need to be added to the list whenever something comes up.
