### ISSUE TITLE
Displayed release date off by one

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin/jellyfin-web#369]
**Describe the bug**
Release date displayed in episode detail page is one day earlier than release date displayed on edit metadata page. 

I am in US CST.

**To Reproduce**
1. Go to tv episode page, notice date displayed
2. Click on 'edit metadata'
3. Scroll down to 'Release Date'

**Expected behavior**
Dates should match.

**Screenshots**

![image](https://user-images.githubusercontent.com/991618/59980341-293f9800-95ba-11e9-97da-61d4b8ccc445.png)

![image](https://user-images.githubusercontent.com/991618/59980343-38bee100-95ba-11e9-9c0e-6c966bcf32e0.png)

**System (please complete the following information):**
 - OS: Docker
 - Browser:Chrome
 - Jellyfin 10.3.5
 - Reverse proxy: no,

**Comment by SenorSmartyPants** [comment]
This still really bugs me for daily shows. Like The Daily Show.

**Comment by Protektor-Desura** [comment]
I am also seeing this exact issue myself in TV shows upcoming schedule. I don't know what time TVDB would be sending because it only has a day of the week and time for the main show, not per episode, and that is only if someone actually enters that info in their database and there is no indication of what timezone is being reported when you set it in the TVDB database.

In the web interface if you go in to TV shows and then click upcoming, it is suppose to show when new shows will be coming out. The problem is everything is off by 1 day. For example "Yesterday" is actually later today. "Thursday, Sep 26" shows Temple, Titans and Van Helsing, but those don't air on Thursday but Friday. Again for "Saturday, Sep 28" shows The Righteous Gemstones, On Becoming a God in Central Florida, Pennyworth, Succession, Glitch and Preacher, which again don't air until Sunday. "Tuesday, Oct 1" shows Stumptown, Wu-Tang: An American Saga, Chicago Fire, Chicago Med and Chicago P.D. which again don't air until Wednesday.

As you can see everything needs to shift to one day later for some reason. So it shouldn't be "Yesterday" but "Later Today" and so forth. Also no the issue isn't bad data from TVDB because Sonarr calendar shows the correct days for shows, which also uses TVDB for it's metadata.

**Comment by anthonylavado** [comment]
Interesting note about the Sonarr bit. That means there’s code we can look at to figure this one out.

**Comment by SenorSmartyPants** [comment]
Please fix this. Thanks.

**Comment by Artiume** [comment]
Spoke to the Sonarr dev's. Sonarr uses Skyhook (not open source) to retrieve everything. 

https://github.com/Sonarr/Sonarr/tree/phantom-develop/src/NzbDrone.Core/MetadataSource/SkyHook

`That’s all done in Skyhook for Sonarr, every episode gets a UTC air time using the network of the series to determine the timezone (and UTC offset). You need to have a list of networks and their probable timezones to be able to convert tvdb dates to utc. sadly, tvdb doesn't do it themselves.`

**Comment by SenorSmartyPants** [comment]
Or don't make it so complicated, just display the same date as in edit metadata.

**Comment by bowiz2** [comment]
@Artiume Maybe a feasible solution is to allow configuration for a time shift per series. TheTVDB saves Air Time in the time zone of the shows location (or for most american shows, EST). So if you could have an option like "Series Native Time Zone" that is user configurable, these edge-cases could be caught pretty easily.

**Comment by Artiume** [comment]
Shouldn't removing the date shift and treat the date as a string work?

**Comment by bowiz2** [comment]
I guess so, yeah. Though I honestly couldn't find any date shifting while I was trawling through the server code. But if it's there, that would work. Would have to be server side though, not client side.
