### ISSUE TITLE
Add Multiple Songs to Playlist

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-web#390]
**Is your feature request related to a problem? Please describe.**
From the forums, a user would like to select and add multiple songs to a playlist at once.

**Describe the solution you'd like**
The ability to select more than one song at a time in the UI, to help with adding to playlists.

**Describe alternatives you've considered**
N/A

**Additional context**
https://forum.jellyfin.org/t/select-multiple-songs-to-add-to-playlist/504?u=anthonylavado

**Comment by oddstr13** [comment]
The functionality for this feature already exists.
A long-press brings up a selection interface in the album view, amongst other places
![image](https://user-images.githubusercontent.com/638706/61664734-b23e1200-acd3-11e9-836b-deb70b15668c.png)

![image](https://user-images.githubusercontent.com/638706/61664842-ef0a0900-acd3-11e9-9355-fdc663cf7a60.png)

It doesn't work perfectly on desktop, as it is a touchscreen feature (I have to move the cursor off the card in order to avoid deselecting again instantly).

It's available in `Banner`, `Poster`, `Poster card`, `Thumb` and `Thumb card` view, but not `List` view, which is most interesting for adding music to playlists, and the only display mode available for the Songs tab, album and playlist song listings.
Does not work with Series season episode listing either.
