### ISSUE TITLE
Unable to change screen ratio

### ISSUE THREAD

**Issue by eladelmadoi** [jellyfin/jellyfin-web#3978]
Hi,
When viewing live stream, click on the right settings wheel, the mini setting screens pop up,
When I'm trying to click on the aspect ratio, it just close the mini setting and go back to the video.

Please advise,
Thanks

**Comment by dmitrylyzo** [comment]
`resolveOnClick: true` doesn't work with browser history.
When we click the menu option, it resolves the promise and we show the next menu, but `onHashChange` closes it because the new dialog is not in the history state.

https://github.com/jellyfin/jellyfin-web/blob/8a75e711e4fad45b28873bb76d35bc2c83309dd7/src/components/dialogHelper/dialogHelper.js#L95
https://github.com/jellyfin/jellyfin-web/blob/8a75e711e4fad45b28873bb76d35bc2c83309dd7/src/components/dialogHelper/dialogHelper.js#L56

We need to wait for the browser history to update before opening a new dialog. But I think we should just remove the `resolveOnClick` functionality.
