### ISSUE TITLE
Add timeout for keystrokes in Search bar

### ISSUE THREAD

**Issue by t0815** [jellyfin/jellyfin-web#4478]
To avoid sending a request to search with every keystroke, it would be best to add a timeout
for keyinput event. At the moment, a request is made immediately on every key input, which makes the search
a bit wonky and unresponsive.

**Comment by thornbill** [comment]
There is a 400ms delay before the search happens https://github.com/jellyfin/jellyfin-web/blob/master/src/components/search/SearchFields.tsx#L43

**Comment by da-anda** [comment]
@thornbill it seems that the code has changed and the line your link is no longer pointing to the correct place. I tried to find the `onSearch` method that seems to be triggered by every key press, but could not find it via Github search. I pretty much would like to completely disable the "instant search" because my RaspberryPi is overwhelmed when this search box is firing 10 requests for almost every letter (when people are slow at typing).

**Comment by thornbill** [comment]
https://github.com/jellyfin/jellyfin-web/blob/master/src/apps/stable/routes/search.tsx#L22
