### ISSUE TITLE
Safari iOS: Navigation Bar won't go away when pinned to Home Screen

### ISSUE THREAD

**Issue by felix920506** [jellyfin/jellyfin-web#4683]
**Describe The Bug**
The navigation bar won't go away when watching fullscreen if accessed from pinned to Home Screen link in safari 

**Steps To Reproduce**

1. Open web client in safari
2. Click on the share icon and add to Home Screen 
3. Open the Jellyfin link from Home Screen
4. Login and play video fullscreen
5. See error

**Expected Behavior**

Navigation bar to disappear after a few seconds 

**Logs**

I don't know how to access these logs 

**Screenshots**

![image](https://github.com/jellyfin/jellyfin-web/assets/25688628/b683757e-5dbf-4e84-b382-d6736cf2d1d1)

**System (please complete the following information):**
 - Platform: iPhone 13 Mini, iOS 16.3.1
 - Browser: Safari
 - Jellyfin Version: 10.8.10

**Additional Context**
This issue doesn't happen in normal safari or the official iOS Jellyfin app (Not Swiftfin)

**Comment by alfred-delacosta** [comment]
I replicated this issue on my iPhone 14. It happens in the PWA version of the JellyFin. I will go ahead and work on this bug.

**Comment by alfred-delacosta** [comment]
After doing a bunch of research and testing other PWA's, I have found that this bug is consistent across all other PWA's on iOS. I tried multiple different ones and all of them have the swipe bar showing no matter what. Twitter was a great test and throughout the entire PWA the swipe bar is showing even if you play a video. I would say that this issue isn't a bug of JellyFin but more of a bug in iOS itself.

To work around this bug, use Safari or download and install the JellyFin app from the AppStore. 

The UIKit allows for the swipe bar to be hidden and both of the apps (Safari and JellyFin) utilize it. See: https://developer.apple.com/documentation/uikit/uiviewcontroller/2887510-prefershomeindicatorautohidden

**Comment by thornbill** [comment]
👍 Thanks for investigating! That confirms what I suspected to be honest.

**Comment by felix920506** [comment]
Still an issue

**Comment by thornbill** [comment]
Should we keep this open? Apple doesn't give web apps any control over this.
