### ISSUE TITLE
Add tests to the project

### ISSUE THREAD

**Issue by Airthee** [jellyfin/jellyfin-web#4872]
Hi !

I see that the project is not covered by tests, am I missing something ?  
I think it would be very important to cover the project with tests.  
I know it's a big job, but we need it to stop regressions, improve stability and maintainability.  
Tests also help to understand the code (to get more contributors &mdash; like me).  
Do you need more arguments ?  

I volunteer to do it.  

I suggest one PR per covered file.  
I will be easy for people to help, by commenting on this post wich file they take.

**Comment by thornbill** [comment]
Yes tests would be great! (You really don't need to convince us. 😉) Unfortunately I think a lot of the legacy code will be virtually impossible to cover with unit tests due to dependencies on side effects. However there has been some movement on a couple different testing initiatives just in the past week!

1. Unit tests:
   * Support for writing tests with vitest is now available. 
   * Currently the only test is for [cardBuilderUtils](https://github.com/jellyfin/jellyfin-web/blob/master/src/components/cardbuilder/cardBuilderUtils.test.js)
   * It would probably be easiest to start writing tests for the [utils](https://github.com/jellyfin/jellyfin-web/tree/master/src/utils) files since they should be mostly self contained. 
2. End-to-end tests:
   * I started a [new repository](https://github.com/thornbill/jellyfin-test-suite) for adding end-to-end tests.
