### ISSUE TITLE
Uncaught runtime errors

### ISSUE THREAD

**Issue by geofflangenderfer** [jellyfin/jellyfin-web#4878]
**Describe The Bug**

```
Uncaught runtime errors:
×
ERROR
Unknown promise rejection reason
    at handleError (webpack-internal:///../node_modules/webpack-dev-server/client/overlay.js:252:58)
    at eval (webpack-internal:///../node_modules/webpack-dev-server/client/overlay.js:275:7)
```

**Steps To Reproduce**

- install jellyfin-web, latest commit
- install jellyfin, latest commit
- start both up
- navigate to localhost:8080 in your web browser
- enter server address 192.168.1.100:8096
**Expected Behavior**

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Platform: [e.g. Linux, Windows, iPhone, Tizen]
 - Browser: [e.g. Firefox, Chrome, Safari]
 - Jellyfin Version: [e.g. 10.6.0]

**Additional Context**

**Comment by thornbill** [comment]
This is a debugging feature of the webpack dev server. You should be able to close the error dialog and continue.

**Comment by Otolone** [comment]
Fixing ViewModel Crashes in Kotlin Multiplatform Web (WASM)

When building Kotlin Multiplatform (KMP) projects targeting the web using Kotlin/Wasm, you may encounter this frustrating runtime error:

Uncaught runtime errors:
ERROR
[object WebAssembly.Exception]
    at handleError (webpack-internal:///...)

This usually occurs when using viewModel() in a @Composable without providing an initializer, like this:

@Composable
fun App(mainViewModel: MainViewModel = viewModel()) {
    ...
}

While this works on JVM-based targets like Android and Desktop, it fails on JS/WASM targets.

Why This Happens

On non-JVM platforms like wasmJs, Kotlin cannot use JVM-style reflection to create instances. viewModel() without parameters depends on reflection under the hood. Because reflection isn’t supported on JS/WASM, it crashes at runtime.

The Fix ✅

Instead of relying on viewModel(), instantiate the ViewModel explicitly and pass it to your Composable:

fun main() {
    ComposeViewport(viewportContainerId = "composeApplication") {
        val viewModel: MainViewModel = MainViewModel()
        App(viewModel)
    }
}

Update your App composable to accept the ViewModel:

@Composable
fun App(mainViewModel: MainViewModel) {
    val greetings by mainViewModel.greetingList.collectAsState()

    Column(
        modifier = Modifier.padding(20.dp),
        verticalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        greetings.forEach { greeting ->
            Text(greeting)
            Divider()
        }
    }
}

Source

JetBrains documentation confirms this in [Compose ViewModel docs](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-viewmodel.html#using-viewmodel-in-common-code):

On non-JVM platforms, objects cannot be instantiated using type reflection. So in common code you cannot call the viewModel() function without parameters: every time a ViewModel instance is created, you need to provide at least an initializer as an argument.

Summary

❌ Don't use viewModel() without an initializer on non-JVM targets.

✅ Manually construct and pass your ViewModel.

This simple fix eliminates runtime crashes on the web and keeps your KMP project smooth across all platforms!
