### ISSUE TITLE
"Recently Added" not showing up for mixed library on jellyfin-web unstable

### ISSUE THREAD

**Issue by memehammad** [jellyfin/jellyfin-web#4900]
**Describe The Bug**
"Recently Added" is missing for mixed libraries on newer versions of jellyfin-web unstable.

**Steps To Reproduce**
1. Update to latest jellyfin-web unstable and server
2. Create library with mixed content
3. See that "Recently added" is missing for that library

**Expected Behavior**
"Recently Added" shows up like it does for any library like it used to a few releases ago (it was still working around the 15th of last month 

**Screenshots**
Old:
![image](https://github.com/jellyfin/jellyfin-web/assets/39221228/f63ea50f-1eec-4621-89ab-28e28f92d4b2)
New:
![image](https://github.com/jellyfin/jellyfin-web/assets/39221228/32c6e4d0-b4e6-4301-96dd-f823db915b87)

**Comment by memehammad** [comment]
still an issue on the latest 10.9 release.

**Comment by Ewillian9** [comment]
i second that, still an issue

**Comment by memehammad** [comment]
> i second that, still an issue

a great workaround for this (since the devs dont like mixed libraries) is to create one library for shows, one for movies or whatever you're mixing and telling them to save metadata as nfos. Hide those libraries from your users and create one library called "mixed movies and shows", library type "shows". Now add both paths for movies and shows and disable all metadata services for this library, so it fetches them from your disk. Expose this library to your users.
 Now you've basically got the same functionality as the mixed library but without any of the issues that come with it.

**Comment by TimGels** [comment]
We suggest not using the mixed library type. We should probably communicate this better in the UI. That aside, this problem is still an issue on latest web and server (master).
For testing I added my movies and shows test libraries to a mixed library type.
![afbeelding](https://github.com/jellyfin/jellyfin-web/assets/43609220/6c378ff6-1d46-4f63-975b-639bcd1f0544)

As reference I also tested my series testing folder with a shows library type:
![afbeelding](https://github.com/jellyfin/jellyfin-web/assets/43609220/11112e6d-be40-45d7-9bbd-065eb61e26cb)
