### ISSUE TITLE
Song details page shows album artist instead of artist

### ISSUE THREAD

**Issue by lifegpc** [jellyfin/jellyfin-web#5481]
**Describe The Bug**
The song detail page shows the album's artist instead of song artist.

**Steps To Reproduce**
1. Have one song which have different album artist and artist.
2. Open song details page.

**Expected Behavior**
The song details page should display the song artist

**Screenshots**
![image](https://github.com/jellyfin/jellyfin-web/assets/41434272/77d4d844-2dd0-442c-b9c8-1d7795b0269c)

**System (please complete the following information):**
 - Platform: Windows
 - Browser: Chrome
 - Jellyfin Version: 10.9.0

**Additional Context**
Seems same issue already reported. #2793

**Comment by loewenheim** [comment]
I can confirm that this still happens on version 10.10.7.
A search result for the song "Vengeance" by New Model Army:
<img width="321" height="356" alt="Image" src="https://github.com/user-attachments/assets/a8078285-4181-425e-a7e5-00e4d9814847" />
And the song's detail page:
<img width="581" height="146" alt="Image" src="https://github.com/user-attachments/assets/68c7eb3b-2f22-4f6b-a8ea-b122269b8951" />
It seems to be a UI problem, not a backend one, because both the search and the detail page return the correct data:
```json
{
	"Name": "Vengeance",
	"ServerId": "72d4125158ca4880a5b6b4812610e764",
	"Artists": [
		"New Model Army"
	],
	"ArtistItems": [
		{
			"Name": "New Model Army",
			"Id": "ed9ba718238c415636b90e5e68730a45"
		}
	],
	"Album": "Undead: 50 Gothic Masterpieces",
	"AlbumArtist": "Various Artists",
	"AlbumArtists": [
		{
			"Name": "Various Artists",
			"Id": "d513b6f57aee39056472063fcb4d751b"
		}
	],
	[…]
}
```
