### ISSUE TITLE
Next steps for TV layout

### ISSUE THREAD

**Issue by dkanada** [jellyfin/jellyfin-web#608]
@dmitrylyzo did you have any other plans for the TV layout improvements? I think the navigation bar and music playback bar should have the same behavior as the Android TV app, which works quite well.

Navigation Bar: When moving left, if there are no focusable elements the navigation bar is opened, and within the navigation bar, any right click will hide the bar.

Music Playback Bar: The bar itself is hidden for the TV layout and a new scroller is shown on the home page that displays cards for every item in the queue. Also, you can navigate to the queue page from the header, which might work well in the navigation bar for the web client.

Another option (my favorite) would be turning the queue into a component and adding it on the right to match navigation bar behavior. This might cause issues with the remote control functionality that currently exists on that page though.

**Comment by dmitrylyzo** [comment]
> did you have any other plans for the TV layout improvements?

Nothing special. Actually, my first PR was merged almost completely. I have skipped some minor changes. But there is some annoying behavior left: when you focus on input, on-screen keyboard appears and captures the focus.
I tried to fix it like this:
1. When you focus on input, it became readonly (this prevents the on-screen keyboard from displaying).
2. On `Enter` or some "printable" key, input became writable (if it was writable initially).
3. To exit "edit mode" you press `Back` button. _(This work in Tizen native app only, where I handle `Back` myself. In webOS and Tizen browser, `Back` is handled like back in browser history)_

**Navigation Bar**
I was asked about navigation bar before. Here are some thoughts  _(from https://github.com/jellyfin/jellyfin-web/pull/544#issuecomment-557219381)_
1. Add/return top menu button to show left menu and focus on its first entry; hide it on blur. _(like in desktop layout)_

2. Show/hide the left menu on focus/blur of its elements. _(disliked this idea while writing - user can use TV layout with a mouse, but will not be able to open the left menu)_
Currently, the left menu is `focuscontainer-y` - only vertical navigation. "Right" button will pop out from it. But for now, it is a bit tricky to get into the left menu. For example, on home screen, you have to move up, because section scrollers is `focuscontainer-x` - release when moving vertically. So, `focusManager` and/or "navigation layout" (assigned focus classes) need to be reworked to be able to focus in left menu by "Left" button.

**Music Playback Bar**
I wanted it to be visible, but being fixed at the bottom, it interrupts the page scrolling.

I just tried AndroidTV in the emulator.

- It seems that the left (navigation) bar is only available on the home screen.

- Queue == playlist? _(playlist can be very very long)_

- Sometimes the song title and/or artist name are too long for the card.

- Music playback control and current progress are only available on `nowplaying` page. _(On real TV, user can also use dedicated buttons on remote control for playback control)_ For user, this is like video player, but for music.

> Also, you can navigate to the queue page from the header, which might work well in the navigation bar for the web client.

This is probably the easiest way. Show/hide button at top menu (if I understand you) like `nowplayingbar` does it now.

> Another option (my favorite) would be turning the queue into a component and adding it on the right to match navigation bar behavior.

Just queue? Or some simplified version of `nowplaying` page?

> This might cause issues with the remote control functionality that currently exists on that page though.

I suppose that the user will have to scroll the scroller to the very right.

**Comment by dkanada** [comment]
> Just queue? Or some simplified version of nowplaying page?

I'm not 100% sure yet, but several of the pages (videoosd, nowplaying, search to name the ones I have in mind) would probably be a lot more usable as components rather than separate pages.

> I suppose that the user will have to scroll the scroller to the very right.

Ah you're right, that's not ideal.

**Comment by EraYaN** [comment]
Alright, so I tried this with the lastest master on webOS 4.5 (latest 2018 OLED).
There are a couple of things:

1. When selecting a media item for the detail page, the loading gif never disappears. (even after using the back button)
4. When selecting an item that does not have any actors (think music video with just an artist and name) the detail page will not ahve any element focussed, for all of these it should probably be the play button in focus. For movies the focus starts at the first subheader (actors for example).
4. In a settings page (for example subtitles), the first selection on the "down" key is somewhere in the middle and not the top element.
5. When playing an the OSD is shown, the right key will advance the playback and move the focus. Left only moves the focus.
6. OSD buttons besides the Pause, the (X) for subtitles and the cog do not show up. (are black) and there do not seem to be any missing (404) items in the network view, it's a fresh build using yarn and webpack.
7. On the detail page for media items it's quite hard to reach the subtitle dropdown if there is only one audio option.
8. On the detail page the poster should probably be skipped for focus, and the play button be selected instead.

And there is probably more, but this is what I saw when I was messing around.

Also these two errors occured:
```
scroller.js?v=10.5.0:206 Uncaught TypeError: ResizeObserver is not a constructor
```
```
itemcontextmenu.js?v=10.5.0:7 Uncaught (in promise) TypeError: Cannot read property 'Policy' of undefined(…)
```

Both is semi regular intervals during navigation.

And this just before the app was hidden by the screensaver while on an item detail page with the busy loading gif still showing.
```
index.html#!/itemdetails.html?id=803e31890c42b6890dace13366068c0e&serverId=cc4c4a7ec6c24b019f1c648c9b226082:1 Uncaught (in promise) undefined
```

**Comment by dmitrylyzo** [comment]
> `scroller.js?v=10.5.0:206 Uncaught TypeError: ResizeObserver is not a constructor`

webpack makes `resize-observer-polyfill` as `ResizeObserver.default`.
_(comment out native ResizeObserver in `site.js` to test in Chrome)_

**Comment by EraYaN** [comment]
Do you have an idea of how to fix that? Seems weird that webpack would move that API surface.

Seems like adding `.default` to that require might fix it. https://github.com/jellyfin/jellyfin-web/blob/21321a8d8ed6f355f2b56da06cacdd65e3e49d9b/src/bundle.js#L57

[Source](https://stackoverflow.com/questions/33704714/cant-require-default-export-value-in-babel-6-x?answertab=active#tab-top)

**Comment by dmitrylyzo** [comment]
> Do you have an idea of how to fix that?

At first I changed `returnFirstDependency` to "globally" fix modules with `export default`
```
    function returnFirstDependency(obj) {
        return obj ? (obj["default"] || obj) : obj;
    }
```
Potentially, `flv.js` will give a similar error _(for the test, I hacked jellyfin to use it)_.

> Seems like adding `.default` to that require might fix it.

Just tried this, and yes, it fixes the error (with `resize-observer-polyfill` only). Not sure about compatibility with different webpack versions (if it is ever needed).

I am not a webpack expert. If there are no options in the webpack itself, then we will have to go your way (probably for each `export default`-modules). _(my way is too global)_

**Comment by EraYaN** [comment]
>Not sure about compatibility with different webpack versions (if it is ever needed).

Well anything past 2.12 I believe should would. But we are solidly on v4 I think. And the `webpack.config.js` file needs to be changed so drastically for any version change that it's okay, as long as it work with the current version. So if you feel it's a good (enough) fix, please make a PR. I like it because it's a neat case by case fix instead of affecting anything global.

**Comment by MrTimscampi** [comment]
I gave some thought over the whole TV thing.

I think the best from a design and usability standpoint would be to adopt @grafixeyehero 's horizontal home as the home layout for TV, without a vertical option. Then we should work on providing horizontal versions of other views, as well as a condensed version of the item details page.

Why? My reasoning is that vertical layouts are a nightmare to navigate with a remote. In a library, for example, the user needs to scroll upwards to go back to the header options. This is annoying, especially with #983 coming, which allows the user to disable the page limit.

A horizontal layout for a remote or keyboard-based UI just makes sense and goes with our desire to differentiate the TV, mobile, and desktop UIs.

So here is my proposed plan:

* Remove horizontal/vertical layout selection from #810 
* Make the horizontal home layout in #810 the one and only home layout for TV
* Merge it
* Start work on horizontal versions of the library pages and a condensed, TV-only, version of the details page.

**Comment by JustAMan** [comment]
Sounds like a plan to me.
Got some mockups?

**Comment by grafixeyehero** [comment]
> 
> 
> I thought about the whole TV thing for a bit.
> 
> I think the best from a design and usability standpoint would be to adopt @grafixeyehero 's horizontal home as the home layout for TV, without a vertical option. Then we should work on providing horizontal versions of other views, as well as a condensed version of the item details page.
> 
> Why? My reasoning is that vertical layouts are a nightmare to navigate with a remote. In a library, for example, the user needs to scroll upwards to go back to the header options. This is annoying, especially with #983 coming, which allows the user to disable the page limit.
> 
> A horizontal layout for a remote or keyboard-based UI just makes sense and goes with our desire to differentiate the TV, mobile, and desktop UIs.
> 
> So here is my proposed plan:
> 
>     * Remove horizontal/vertical layout selection from #810
> 
>     * Make the horizontal home layout in #810 the one and only home layout for TV
> 
>     * Merge it
> 
>     * Start work on horizontal versions of the library pages and a condensed, TV-only, version of the details page.

maybe if this help cheak it out it a bit old repo for tv based on html5 https://github.com/grafixeyehero/jellyfin-html5/tree/make-jellyfincompateble
