### ISSUE TITLE
 10.10.0 Experimental PGS subtitle render alignment

### ISSUE THREAD

**Issue by bibliomecha** [jellyfin/jellyfin-web#6273]
**Describe The Bug**
When 'Experimental PGS subtitle rendering' is enabled, **some** subtitle lines aren't centered.
Instead, the alignment **might**:
a. match the start of the line that will be displayed next.
b. match the start of the line that appeared previously.

For example, if the current line is shorter than the next, the current line **might** be shifted towards the left of the screen. The misaligned subtitle lines are centered when the PGS is burned in.

The issue is 100% reproducible when viewing the same subtitle line again. 

Rendered:
![pgs_render](https://github.com/user-attachments/assets/33034e90-65fb-416d-b763-379149075e3d)

Burned:
![pgs_burned](https://github.com/user-attachments/assets/137947b9-d974-4922-ba0e-94deb10b6b81)

**Steps To Reproduce**
1. On the client, ensure 'Experimental PGS subtitle rendering' is enabled in Settings -> Subtitles.
2. Watch a video with PGS subtitles enabled.
3. Notice if a subtitle line is shifted towards the left of the screen, aligning itself with the previous or next line.
4. Disable 'Experimental PGS subtitle rendering' and confirm the same subtitle line is correctly centered with burned in PGS.

**Expected Behavior**
The alignment of rendered PGS subtitles should match that of the burned in PGS subtitles.

**System:**
 - Platform: Linux
 - Browsers: Firefox, Chrome
 - Jellyfin Version: 10.10.0

**Comment by nyanmisaka** [comment]
The author of libpgs-js @Arcus92 might know something about this.

**Comment by Arcus92** [comment]
Hi @bibliomecha,
I checked the code in FFmpeg that renders PGS and couldn't find any special offset rule. I guess the video and overlay are somehow misaligned. Are you using a custom theme or custom css on your instance?

I noticed that the subtitle overlay will not respect your video-fill-mode / aspect ratio (auto, cover, stretched). Currently it will only work for auto. I will address this. Do you use the other settings?

If not, could you provide a screenshot of your issue.

**Comment by bibliomecha** [comment]
Hi @Arcus92,

I'm using the default theme with no custom css. 
My aspect ratio is set to auto. 

I've added screenshots to my original post.

**Comment by Arcus92** [comment]
Thanks @bibliomecha,
You screen shot gave me a good idea what happened here. It looks like it used the wrong / previous 'window' when drawing the second subtitle. I'll go through the code and try to find it.

I don't know the copyright situation for subtitles, so please don't upload them here. But if ... by change ... you have the .sup file, could you share it to the email address in my GitHub profile? That would help me to confirm the issue.

**Comment by nyanmisaka** [comment]
- https://patchwork.ffmpeg.org/project/ffmpeg/patch/CWLP123MB6857374E8CB6FF8E1BFF4940C6469@CWLP123MB6857.GBRP123.PROD.OUTLOOK.COM/

- https://github.com/HandBrake/HandBrake/blob/master/contrib/ffmpeg/A19-lavc-pgssubdec-Add-graphic-plane-and-cropping.patch

@Arcus92 Probably not relevant, but this patch may fix some issues in the PGSSUB decoder in FFmpeg. Since you have researched a lot on PGSSUB, what do you think of it? Can libpgs-js also benefit from those changes?

**Comment by Arcus92** [comment]
Hi @bibliomecha,
I updated the library and prepared a patch. 
Could you please confirm that the subtitle is aligned correctly in this version of the client: https://b83fcf0e.jellyfin-web.pages.dev/
You can can click 'Switch server' and connect to your local one since this is just a client issue. Please remember to enable the 'Experimental PGS subtitle rendering' option - _and click 'Save'_ - in the subtitle settings again.

**Comment by bibliomecha** [comment]
Hi @Arcus92,

Using that version of the client, I am unable to reproduce the issue by checking subtitle lines that were misaligned previously. Nice one!

**Comment by thornbill** [comment]
Should be fixed when 10.10.2 is released.
