### ISSUE TITLE
Cleaning up Home, DVR, & TV Shows Menu Items & Screens

### ISSUE THREAD

**Issue by classicjazz** [jellyfin/jellyfin-web#750]
**Describe the bug**
I use JellyFin for Live TV, DVR, and TV Shows (among other media). However, I find the menu items and their results very confusing and unintuitive. 

**To Reproduce**
In my configuration, recorded shows are saved in a library/folder ("DVR"), separate from TV Shows and Movies libraries for two reasons:

* for security, only the DVR folder is write-enabled (TV Shows and Movies are read-only), and
* recorded shows in the DVR folder are rapidly watched and then deleted. Conversely, videos in the TV Shows and Movies folders are kept permanently.

**Expected behavior**
Following are my issues and proposed changes:

(1) Home Screen

* Don't show "Home | Favorites" if no shows are favored.
	- Realistically, most people won't favor their shows (i.e. why keep stored or recorded programs that aren't a favorite and, then, why mark everything you keep as a favorite?). 
	- If shows aren't favored, then this will result in a blank screen and needlessly add a half-functional menu bar.

<img width="789" alt="Home menu bar" src="https://user-images.githubusercontent.com/7338491/73410736-1ec44a00-42d1-11ea-80af-426a871085a7.png">

* The Live TV section on the Home screen is missing the "Channels" menu item. Compare the Live TV library that has "Programs | Guide | Channels | Recordings | Schedule | Series"

<img width="620" alt="Home live tv menu bar" src="https://user-images.githubusercontent.com/7338491/73410753-2be13900-42d1-11ea-9b25-8ba40e8179c0.png">

* The Live TV icon should show a mashup of currently airing shows' poster art, similar to all other libraries in JellyFin, rather than a generic blue icon.

<img width="875" alt="My media live tv icon" src="https://user-images.githubusercontent.com/7338491/73410775-3996be80-42d1-11ea-94df-f8dace434be5.png">

(2) DVR

* I recommend a DVR library option that has the same categories as the Live TV shows menu items. Currently, we must use TV Shows library option. The Live TV shows menu items are much more valuable for the DVR library.

<img width="846" alt="TV shows suggestions" src="https://user-images.githubusercontent.com/7338491/73410827-5f23c800-42d1-11ea-83b2-a145ce2e0711.png">

(3) TV Shows

* Remove Suggestions menu item. This currently shows only other shows in your TV Show library. There's little point in suggesting a subset of your TV show library. Logically, every show in your library is of interest to you.

<img width="846" alt="DVR shows" src="https://user-images.githubusercontent.com/7338491/73410797-4a473480-42d1-11ea-894d-9f33bba41022.png">

* Remove Upcoming menu item. This currently only shows: "Please ensure downloading of Internet metadata is enabled."

<img width="846" alt="TV shows upcoming" src="https://user-images.githubusercontent.com/7338491/73410847-75318880-42d1-11ea-9478-8a456b466e20.png">

* Remove Networks menu item. There is little value to showing the TV network on which a TV show originally aired. Meanwhile this assumes that TV show data includes the originally aired TV network.

<img width="846" alt="TV shows networks" src="https://user-images.githubusercontent.com/7338491/73410850-7bc00000-42d1-11ea-90fe-b5b34369e48a.png">

* Remove Episodes menu item. It shows every single episode of every single TV Show, potentially thousands of episodes!

<img width="846" alt="TV shows episodes" src="https://user-images.githubusercontent.com/7338491/73410861-82e70e00-42d1-11ea-9c90-b0d923fb5b8b.png">

**Comment by Artiume** [comment]
So yeah, livetv needs to be fixed up a bit, luckily most of those are frontend tweaks. 

What I'm mostly concerned about is this. It will be tricky because it's backend repairs. 
https://github.com/jellyfin/jellyfin/issues/2336

I'll add some pictures to show how my setup runs when I get a chance.

**Comment by Artiume** [comment]
I found this image online and made it my background picture.
![image](https://user-images.githubusercontent.com/20715731/73601574-f8e9b000-4531-11ea-81f8-cb54353d36da.png)

Everything is saved in /media/recordings. library name is Recordings
![image](https://user-images.githubusercontent.com/20715731/73601589-2898b800-4532-11ea-920d-cc1c79f8979e.png)

Inside the library
![image](https://user-images.githubusercontent.com/20715731/73601565-d22b7980-4531-11ea-9091-b24b39f13f5d.png)

Inside my DVR settings
![image](https://user-images.githubusercontent.com/20715731/73601606-81685080-4532-11ea-81fa-8c41a6a75cea.png)
![image](https://user-images.githubusercontent.com/20715731/73601620-bf657480-4532-11ea-885c-10537ac9a1d8.png)

**Comment by DMouse10462** [comment]
Sort of a point by point review of those suggestions:

1a. Favorites could definitely be reworked a bit, but I think that a complete removal of the entry point is a bit overkill. At the very least, a prompt like "No favorites - press the heart button on anything in your media library to add it here for quick access!" could (1) make the empty page look less like a bug and (2) invite users to begin using the feature.

3 (overall). Removing menu items simply because one user does not use them seems to be a step in the wrong direction, but I can see where certain use cases could make a lot of these unnecessary. I think this is something that could be solved in a manner similar to the Custom CSS/branding feature, but since I don't think you can apply custom CSS based on the data-index of an element the current options do not allow for this.

3a. While your use case may be that all of your library is of interest to you, this may not be the case for a family sharing a common library. One person likes their mystery shows and smooth jazz, another likes horror and heavy metal, and yet another person likes their K-pop, anime, and classic Disney movies. While you could separate your libraries out based on these tastes, maybe the anime fan could really get into some of the murder mysteries after watching a detective anime and Jellyfin would've been their entry point into that had the suggestions tab still existed. 

Personally, I'd love to see a suggestions button on the home page so I can be recommended content across all of my libraries. I'm curious to see how the suggestions are implemented, and if there's any way we can improve on them (though that's a server topic).

3b. Looks good to me; are your series actually continuing? Also, that page can definitely be cleaned up presentation-wise (and link to something not completely broken). Here's one of mine:

![Screenshot from 2020-02-02 01-49-57](https://user-images.githubusercontent.com/2002606/73604428-89d68080-455e-11ea-9f83-c0df44bf21ea.png)

3c. Networks has actually been useful to me a few times; what is that one British crime drama I have? I don't have a lot of British shows, so seeing a big button that screams ITV at me helped narrow it down a lot. It's also a fun way to see what kind of shows air on a particular channel, especially anime (I can definitely see a pattern for some networks).

3d. I do think that the practical uses for this screen are a bit low, but it's definitely fun to look at it with sorting rules applied. Premiere date shows me that a couple of my favorite shows I didn't watch back when they ran were releasing episodes week-by-week in the same season (but on two different channels). 

Practical? No. Fun, yes! Part of the charm of having a dedicated library for all of this is media discovery, and that's why I think suggestions, weird sorting options, and other fun things like that make it feel like I really _do_ have my own personal Netflix.

**Comment by Artiume** [comment]
I agree with @DMouse10462 with his reasoning. I never saw a useful for the networks filter until I used it one day lol. 

And suggestions just needs improvement for genres. Once that's done, we can make improvements for adding them directly to the homepage. Overall, removal should be done if there's no use for the feature, but the majority of the features are useful, they're just broken in some form lol 

`The Live TV section on the Home screen is missing the "Channels" menu item. Compare the Live TV library that has "Programs | Guide | Channels | Recordings | Schedule | Series"`

I tried fixing it with this but it appears to controlled somewhere else
https://github.com/Artiume/jellyfin-web/pull/14

**Comment by classicjazz** [comment]
Thanks everyone for your constructive feedback. There will likely always be someone who finds a particular feature valuable. (It's the Microsoft Office toolbar problem). Personally, I prefer fewer menu items and simplicity of UX customization.

Here's what I recommend to address this issue:

1.) **Fix the Live TV home screen section** so that it mirrors the Live TV section.
https://github.com/Artiume/jellyfin-web/pull/14

(Thank you @Artiume for kickstarting this).

2.) **Add a DVR library option** (which has the same menu items as Live TV currently does... since it is simply previously recorded Live TV). Users can then choose whether to keep their recorded TV separate from their TV shows library (defining it as a DVR library) or to commingle them (defining it as a TV Shows library).

3.) Re the **TV Shows library menu items** (and likely for DVR and Movies libraries too), I recommend an **advanced settings option** to customize/uncheck menu items. For example, I only care about all shows, recently added ones and genres. So I would uncheck all others. 

The advantage of user-selected menu items is two fold: 
(1) easy for average users to customize without knowing CSS and 
(2) all JellyFin clients (such as a future Apple TV client) would inherit the same configuration (not just HTML clients).

**Comment by Artiume** [comment]
> 2.) Add a DVR library option (which has the same menu items as Live TV currently does... since it is simply previously recorded Live TV). Users can then choose whether to keep their recorded TV separate from their TV shows library (defining it as a DVR library) or to commingle them (defining it as a TV Shows library).

So this is sort of capable already within the DVR. You can tell it to save to different folders. If you want them mixed in, make a Mixed Content library and it's back to being segregated but in a single library. 

> 3.) Re the TV Shows library menu items (and likely for DVR and Movies libraries too), I recommend an advanced settings option to customize/uncheck menu items. For example, I only care about all shows, recently added ones and genres. So I would uncheck all others.

So yeah, there's stuff we could do here. Like, right now, my kid shows are stuffed into their own folder instead of being mixed into the rest just so I can create a special kids library. Being able to filter specific channels or recordings for a specific group is definitely a wanted feature.

> (1) easy for average users to customize without knowing CSS

Fixing this for everyone ;) 
https://github.com/jellyfin/jellyfin-docs/pull/215

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/
