### ISSUE TITLE
Allow downloading of whole shows and seasons

### ISSUE THREAD

**Issue by viggy96** [jellyfin/jellyfin-web#765]
Right now, if the user wants to download content for offline viewing, it has to be done one episode at a time. It would be much better if this could be done in batches as well, such as by season, or for entire shows.

**Comment by MrTimscampi** [comment]
Hi @viggy96 , this is more of a feature request than an issue, so the proper place for it would be [on our Fider](https://features.jellyfin.org/).

The current Download entry in the menus isn't really made for offline viewing per se, although it's a nice side effect of it.  
I don't expect we'll be adding a way to download an entire show or season with the current system, since a TV show can be pretty heavy and it would likely require a bunch of work server-side to package the seasons/shows for download.

However, there's already a feature request for offline sync [here](https://features.jellyfin.org/posts/218/jellyfin-mobile-app-offline-downloads) on which you can vote to show your support for the feature.
