### ISSUE TITLE
Display all episodes of one season TV shows on core page

### ISSUE THREAD

**Issue by hamburglar2160** [jellyfin/jellyfin-web#892]
![image](https://user-images.githubusercontent.com/61879508/76098362-4e810480-5f97-11ea-9019-e7418289d00d.png)

For shows (and documentaries) with only one season or no explicit season 1, provide the option to display all of these episodes on the show's core page instead of having to navigate to another page.

**Comment by Matt07211** [comment]
Also, this should be applicable for series that you enable Absolute ordering on!

**Comment by kinghat** [comment]
its like there should be two additional options for displaying TV shows. sometimes its just one video that doesnt need a season that would display like a movie, and then the time when theres a few videos but its not in a season and doesnt need to be subdivided like your issue is about. and then you have the regular way TV shows should be displayed. 

documentaries can be one video or a few videos but dont need the season sublevel

**Comment by Matt07211** [comment]
Any chance we could reopen this? Or did this get moved to the jellyfin feature request system?

**Comment by MrTimscampi** [comment]
It's available on the feature request system if you'd like to vote for it or discuss it: https://features.jellyfin.org/posts/332/non-seasonal-one-running-season-optio

**Comment by wizard-zoso** [comment]
It seems Emby is winning in that department unless we move forward

**Comment by cvium** [comment]
It's not a competition
