### ISSUE TITLE
Selector for multiple audio streams inside player for LiveTV

### ISSUE THREAD

**Issue by flowlee** [jellyfin/jellyfin-web#921]
**Description**
There is currently no way to switch between multiple audio tracks from inside the player UI when watching a LiveTV stream.

**To Reproduce**
1. Play a channel with multiple audio tracks
2. Try to change to a different audio track while the video is playing ;)

**Expected behavior**
There should be a UI element to select a different audio track in the player overlay

**System**
 - OS: Docker on Ubuntu Server 16.04, TV stream via TVHeadend plugin
 - Browser: Firefox
 - Jellyfin Version: 10.5.0

**Comment by MrTimscampi** [comment]
Please redirect feature requests and suggestions to https://features.jellyfin.org/

**Comment by DMouse10462** [comment]
This may actually be a true bug in the sense that the audio stream options aren't being passed to the client or player (I haven't looked at it closely enough yet besides confirming that my Live TV does indeed have multiple audio tracks coming from TVHeadend, but are not selectable in the UI). I, and I'm sure others (including the user who opened this issue), believe that UI behaving in an inconsistent way from what other views would lead the user to expect is considered a bug. I make reference to this in #66, but the same concept applies here. 

Given this, I believe the issue should be reopened with the tags <bug> and <ui & ux>. I will further research this and see if I can figure out whether it's an issue of the Media Info not existing, the TVHeadend plugin somehow not providing the audio tracks, the server not providing the audio tracks since it's transcoding (?) blindly without stored Media Info, or the client not using some piece of information being given to it by the server. If one of the former is the issue, I would suggest transferring and re-tagging this issue.

**Comment by DMouse10462** [comment]
Just as an additional note, additional audio tracks on a Live TV stream are especially important for alternate languages and descriptive audio tracks; a primary example would be the secondary audio track common in the US for Spanish language or DVS (Descriptive Video Service) content.

**Comment by MrTimscampi** [comment]
> the audio stream options aren't being passed to the client or player

Then the issue should be transferred to the server, the web client has no effect on this. @jellyfin/core
