### ISSUE TITLE
Arrow keys can adjust volume and fast forward / rewind simultaneously

### ISSUE THREAD

**Issue by dgcole** [jellyfin/jellyfin-web#957]
**Describe the bug**
The volume can be adjusted with the left / right arrow keys after adjusting the volume slider with the mouse, but it will also fast forward / rewind the video. 

**To Reproduce**
1. Play a video
2. Adjust the volume by moving the slider with the mouse
3. Press the left / right arrow keys
4. The video will fast forward / rewind AND the volume will also be adjusted

**Expected behavior**
One would expect that a single press of the left / right arrow key would only be able to fast forward / rewind the video OR adjust the volume, depending on the context.

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 80.0
 - Jellyfin Version: 10.5.1

**Comment by kip-13** [comment]
This would be fixed creating a dynamic prop in `volumeSliderTimer` and that element is an `emby-slider`.

Something like:

```js
if (clickedElement.isolateAction) return
```

These are the files and lines related.

https://github.com/jellyfin/jellyfin-web/blob/2bda5f0277be6a1df2ed69cd315231ad8d5281f9/src/controllers/playback/videoosd.js#L1276

https://github.com/jellyfin/jellyfin-web/blob/2bda5f0277be6a1df2ed69cd315231ad8d5281f9/src/controllers/playback/videoosd.js#L1425-L1430

https://github.com/jellyfin/jellyfin-web/blob/2bda5f0277be6a1df2ed69cd315231ad8d5281f9/src/elements/emby-slider/emby-slider.js#L215-L227

Later this prop could be checked in the handler of the global event registered inside the controller:

https://github.com/jellyfin/jellyfin-web/blob/2bda5f0277be6a1df2ed69cd315231ad8d5281f9/src/controllers/playback/videoosd.js#L1097-L1106

https://github.com/jellyfin/jellyfin-web/blob/2bda5f0277be6a1df2ed69cd315231ad8d5281f9/src/controllers/playback/videoosd.js#L1131-L1140

I was thinking too in `stopPropagation()` but both events are different, so that approach won't work.
